---
displayName: NodeJS Express Web Application
description: Stack with NodeJS 10
tags: ["NodeJS", "Express", "ubi8"]
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/dependencies/che-devfile-registry/images/type-node.svg
globalMemoryLimit: 1686Mi
