---
displayName: C/C++
description: C and C++ Developer Tools stack
tags: ["c", "c++", "clang", "g++", "make", "cmake"]
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/dependencies/che-devfile-registry/images/type-cpp.svg?sanitize=true
globalMemoryLimit: 1686Mi
