---
displayName: "PHP Simple"
description: PHP Stack with PHP 7.1 and simple web application
tags: ["PHP", "Apache", "RHEL"]
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/dependencies/che-devfile-registry/images/type-php.svg?sanitize=true
globalMemoryLimit: 2430Mi
