---
displayName: Java Vert.x
description: Java stack with OpenJDK 8 and Vert.x demo application
tags: ["Java", "OpenJDK", "Maven", "Vertx"]
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/dependencies/che-devfile-registry/images/type-spring-boot.svg
globalMemoryLimit: 2674Mi
