---
displayName: Thorntail REST HTTP
description: Quickstart to expose a REST Greeting endpoint using Thorntail
tags: ["Java", "OpenJDK", "Maven", "EAP"]
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/dependencies/che-devfile-registry/images/type-thorntail.svg
globalMemoryLimit: 2674Mi
