---
displayName: Red Hat Fuse
description: Red Hat Fuse
tags: ["OpenJDK", "Maven", "EAP"]
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/dependencies/che-devfile-registry/images/type-fuse.svg?sanitize=true
globalMemoryLimit: 2816Mi
