---
displayName: Go
description: Stack with Go 1.11.5
tags: ["Go"]
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/dependencies/che-devfile-registry/images/type-go.svg
globalMemoryLimit: 1686Mi
